package com.email.email_assistant.service;

import com.email.email_assistant.model.EmailRequest;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.List;
import java.util.Map;

@Service
public class EmailGeneratorService {

    private final WebClient webClient;

    @Value("${gemini.api.url}")
    private String geminiApiUrl;

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    public EmailGeneratorService(WebClient.Builder webClientBuilder) {
        this.webClient = webClientBuilder.build();
    }

    public String generateEmailReply(EmailRequest emailRequest) {

        // Build the prompt text
        String promptText = buildPrompt(emailRequest);

        // Build the request body structure as required by Gemini
        Map<String, Object> part = Map.of("text", promptText);

        Map<String, Object> contentItem = Map.of(
                "parts", List.of(part)
        );

        Map<String, Object> requestBody = Map.of(
                "contents", List.of(contentItem)
        );

        try {
            System.out.println("Calling Gemini API at: " + geminiApiUrl);
            System.out.println("Request body: " + requestBody);

            String response = webClient.post()
                    .uri(geminiApiUrl)
                    .header("Content-Type", "application/json")
                    .header("x-goog-api-key", geminiApiKey)           // Required header
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            return extractResponseContent(response);

        } catch (Exception e) {
            return "Error calling Gemini API: " + e.getMessage();
        }
    }

    private String extractResponseContent(String response) {
        if (response == null || response.isEmpty()) {
            return "No response from Gemini API.";
        }

        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(response);

            JsonNode candidates = root.path("candidates");
            if (candidates.isArray() && candidates.size() > 0) {
                JsonNode parts = candidates.get(0)
                        .path("content")
                        .path("parts");
                if (parts.isArray() && parts.size() > 0) {
                    return parts.get(0).path("text").asText();
                }
            }
            return "No content generated by Gemini API.";
        } catch (Exception e) {
            return "Error parsing Gemini response: " + e.getMessage();
        }
    }
    private String buildPrompt(EmailRequest emailRequest) {

        String tone = (emailRequest.getTone() != null && !emailRequest.getTone().isBlank())
                ? emailRequest.getTone().toLowerCase()
                : "professional";

        String toneInstruction;

        switch (tone) {
            case "friendly":
                toneInstruction = """
                    - Use warm, approachable, and conversational language.
                    - Keep it polite but relaxed.
                    - Avoid overly formal corporate phrases.
                    - Make it sound human and personable.
                    """;
                break;

            case "formal":
                toneInstruction = """
                    - Use highly professional and respectful language.
                    - Maintain corporate etiquette.
                    - Avoid contractions (e.g., use "I am" instead of "I'm").
                    - Keep the structure structured and polished.
                    """;
                break;

            case "apologetic":
                toneInstruction = """
                    - Express sincere apology where appropriate.
                    - Take responsibility if necessary.
                    - Reassure the recipient professionally.
                    - Keep tone calm and empathetic.
                    """;
                break;

            case "confident":
                toneInstruction = """
                    - Use assertive and decisive language.
                    - Avoid uncertainty or hesitation words.
                    - Keep it professional but strong.
                    """;
                break;

            default:
                toneInstruction = """
                    - Maintain a balanced professional tone.
                    - Be clear, concise, and business-appropriate.
                    """;
                            }

                    return """
                    You are an expert corporate communication assistant.
                    
                    Your task is to generate a clear, well-structured, and professional email reply.
                    
                    STRICT RULES:
                    - Do NOT include a subject line.
                    - Do NOT repeat the original email.
                    - Keep the response concise but complete.
                    - Ensure proper greeting and closing.
                    - Ensure grammar is correct.
                    - Do not add unnecessary information.
                    
                    TONE REQUIREMENTS:
                    %s
                    
                    Structure the email as:
                    1. Greeting
                    2. Acknowledgment
                    3. Main response
                    4. Closing line
                    5. Professional sign-off (e.g., "Best regards,")
                    
                    Original Email:
                    %s
                    
                    Generate only the final email reply:
                    """.formatted(toneInstruction, emailRequest.getEmailContent());
    }
}